tools:
  review_on_submit:
    baml_entrypoint: {
      class: "ReviewOnSubmitResult",
      function: "ReviewOnSubmit"
    }
    schema: "baml_src/tools/review_on_submit.baml"
    signature: "review_on_submit"
    docstring: "reviews changes before submission"
    arguments: []
