tools:
  edit:

    #points to baml entrypoint
    baml_entrypoint: "EditRewrite" 
    #points to baml schema ? --> check this
    schema: "baml_src/tools/edit_rewrite.baml" 
    signature: |
      edit <text>
    docstring: >
      Replace the currently displayed lines with <text>.
    arguments:
      - name: text
        type: string
        description: "the text to replace the currently displayed lines with"
        required: true